name: Build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '5.0.x'

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      working-directory: ${{github.workspace}}/build
      run: cmake ${{github.workspace}} -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/Runtimes

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --config Release

    - name: Install
      working-directory: ${{github.workspace}}/build
      run: cmake --install .

    # fixes sporadic build fails on Windows (https://github.com/actions/setup-dotnet/issues/155)
    - name: Clean
      run: dotnet clean -c Release && dotnet nuget locals all --clear

    - name: Test
      working-directory: ${{github.workspace}}
      run: dotnet test

    - name: Upload Binaries
      uses: actions/upload-artifact@v2
      with:
        path: ${{github.workspace}}/Runtimes/*

  pack:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/download-artifact@v2
      with:
        name: artifact
        path: ${{github.workspace}}/Runtimes
    - run: ls -R

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '5.0.x'

    # fixes sporadic build fails on Windows (https://github.com/actions/setup-dotnet/issues/155)
    - name: Clean
      run: dotnet clean -c Release && dotnet nuget locals all --clear

    - name: Pack
      run: dotnet pack -c Release

    - name: Upload .nupkg
      uses: actions/upload-artifact@v2
      with:
        path: ${{github.workspace}}/TinyEmbree/bin/**/*.nupkg

    - name: Publish on version change
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: TinyEmbree/TinyEmbree.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
