name: Build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Build
      working-directory: ${{github.workspace}}
      run: ./make.ps1
      shell: pwsh

    - name: Upload Binaries
      uses: actions/upload-artifact@v3
      with:
        path: ${{github.workspace}}/runtimes/*

  pack:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - uses: actions/checkout@v3

    - uses: actions/download-artifact@v3
      with:
        name: artifact
        path: ${{github.workspace}}/runtimes

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Pack
      run: dotnet pack -c Release

    - name: Upload .nupkg
      uses: actions/upload-artifact@v3
      with:
        path: ${{github.workspace}}/TinyEmbree/bin/**/*.nupkg

    - name: Publish on version change
      uses: alirezanet/publish-nuget@v3.0.4
      with:
        PROJECT_FILE_PATH: TinyEmbree/TinyEmbree.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
